version: '3.8'

services:
  front:
    build: .
    command: 'yarn serve'
    image: challenge-front
    ports:
    - '8080:8080'
    volumes:
    - .:/code
    environment:
    - VUE_APP_BASE_URL=http://localhost:3000/api/v1/
